version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432  # make sure you don't have another container running on 5432

    environment:
      - POSTGRES_DB=gokapture
      - POSTGRES_USER=akshay
      - POSTGRES_PASSWORD=akshay1754
    networks:
      - my_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - my_network


  app:
    build: .
    image: akshayp1754/gkapture_assignment
    container_name: node_app
    environment:
      DB_NAME: gokapture
      DB_USER: akshay
      DB_PASSWORD: akshay1754
      DB_HOST: db  # Use the service name defined in docker-compose.yml
      PORT: 5000
      JWT_SECRET: Hare_Krishna
    ports:
      - 5000:5000
    depends_on:
      - db
    networks:
      - my_network

networks:
  my_network:  
      
    